### ISSUE TITLE
build: protobufjs throws npm checkExecSyncError

### ISSUE THREAD

**Issue by henrywu2019** [lyft/clutch#138]
**Description**

This is a follow-up issue of the last one I filed. I ran `make` and got this error now:

```
info: compiling javascript bundle
installing semver@^5.5.0
child_process.js:644
    throw err;
    ^

Error: Command failed: npm --silent install semver@^5.5.0
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at modInstall (~/git.repo/lyft/clutch/build/bin/protobufjs-1d626f84db4a4f339004609f654a9f24a211b716/node_modules/protobufjs/cli/util.js:129:19)
    at Object.exports.setup (~/git.repo/lyft/clutch/build/bin/protobufjs-1d626f84db4a4f339004609f654a9f24a211b716/node_modules/protobufjs/cli/util.js:140:9)
    at Object.<anonymous> (~/git.repo/lyft/clutch/build/bin/protobufjs-1d626f84db4a4f339004609f654a9f24a211b716/node_modules/protobufjs/cli/pbjs.js:7:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Makefile:23: recipe for target 'api' failed
make: *** [api] Error 1
```

**Expected Behavior**
Build is successful

**Actual Behavior**
Build failed

**Version**
master repo

**Other Context**
The yarn issue is fixed anyway. Thanks.

**Comment by danielhochman** [comment]
@henrywu2019 glad to hear the yarn bug is fixed.

what version of node js is installed on your machine?

`node --version` or maybe `nodejs --version`? also `npm --version`?

also what operating system are you running?

**Comment by henrywu2019** [comment]
I am running with Linux ubuntu 18.04. Maybe that is the reason. Let me try to fix it myself. Thanks tons.

**Comment by danielhochman** [comment]
generally with ubuntu you want to uninstall whatever node is provided by the system and instead install it from https://github.com/nodesource/distributions

i run ubuntu as well, and use the nodesource distributions.

**Comment by danielhochman** [comment]
closing as stale, please reopen if you're still having trouble.
