### ISSUE TITLE
ci: discrepancies between ci and local setups

### ISSUE THREAD

**Issue by Augustyniak** [lyft/clutch#417]
**Description**

1. Add optional chaining to `clutch.config.js` file (i.e. `const faults = e.scenario?.faults`)
1. Run `make frontend-dev` locally - it succeeds.
1. Run `make frontend-lint` locally - it succeeds.
1. Push your changes to the remote branch.
1. Open a draft of a PR/PR

**Expected Behavior**
CI `frontend build` and `frontend lint` jobs complete with a success.

**Actual Behavior**
CI `frontend build` and `frontend lint` jobs fail with the following error:

```
$ yarn workspace @clutch-sh/tools registerWorkflows $PWD/src
$ node workflow-registrar.js /home/runner/work/clutch-private/clutch-private/frontend/src
/home/runner/work/clutch-private/clutch-private/frontend/src/clutch.config.js:136
              const faults = e.scenario?.faults;
                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

```

**Version**

**Other Context**
CI uses node.js to parse/evaluate `clutch.config.js` while local builds do not do this - I guess this is why we see the differences in the results of local and remote builds. That being said, this kind of a setup makes developing cumbersome since you can learn about some of the issue only after pushing them to the remote.

This issue is related to https://github.com/lyft/clutch/issues/416.

**Comment by dschaller** [comment]
One possible option here is to restrict the bounds of node to below 14 but it would mean anyone running node 14 wouldn't be able to run Clutch. I'm not entirely sure of a way to bubble this up to users before hitting CI since we only enforce a minimum of node 12 at the moment. One possibility is to run against a suite of node versions in CI to make it clear that it would only be passing on version 14 and not 12 or 13.
